In [1]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt                                       
from sklearn.model_selection import train_test_split, cross_val_score 
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report 

In [2]:
df = pd.read_csv('./data.csv')
df

acidity  indigestion  headache  blurred_and_distorted_vision  \
0           1            1         0                             1   
1           0            1         1                             1   
2           1            0         1                             1   
3           1            1         0                             1   
4           1            1         1                             0   
...       ...          ...       ...                           ...   
1066        0            1         0                             0   
1067        1            1         0                             0   
1068        0            1         0                             0   
1069        0            1         0                             0   
1070        0            1         0                             0   

      excessive_hunger  muscle_weakness  stiff_neck  swelling_joints  \
0                    1                0           1                0   
1                    1                0           1                0   
2                    1                0           1                0   
3                    1                0           1                0   
4                    1                1           1                0   
...                ...              ...         ...              ...   
1066                 0                0           0                0   
1067                 0                0           0                0   
1068                 0                0           0                0   
1069                 0                0           0                0   
1070                 0                0           0                0   

      movement_stiffness  depression  ...  blood_in_stool  gnawing  \
0                      0           1  ...               0        0   
1                      0           1  ...               0        0   
2                      0           0  ...               0        0   
3                      0           0  ...               0        0   
4                      0           0  ...               0        0   
...                  ...         ...  ...             ...      ...   
1066                   0           0  ...               0        0   
1067                   0           0  ...               0        0   
1068                   0           0  ...               0        0   
1069                   0           0  ...               0        0   
1070                   0           0  ...               0        0   

      upper_abdomain_pain  fullness_feeling  hiccups  abdominal_bloating  \
0                       0                 0        0                   0   
1                       0                 0        0                   0   
2                       0                 0        0                   0   
3                       0                 0        0                   0   
4                       0                 0        0                   0   
...                   ...               ...      ...                 ...   
1066                    0                 0        0                   1   
1067                    0                 0        0                   1   
1068                    0                 0        0                   0   
1069                    0                 0        0                   0   
1070                    0                 0        0                   1   

      heartburn  belching  burning_ache  prognosis  
0             0         0             0   Migraine  
1             0         0             0   Migraine  
2             0         0             0   Migraine  
3             0         0             0   Migraine  
4             0         0             0   Migraine  
...         ...       ...           ...        ...  
1066          0         1             0  Gastritis  
1067          0         0             0  Gastritis  
1068          1         1             0  Gastritis  
1069          0 

In [3]:
df.drop_duplicates(inplace=True)
df

acidity  indigestion  headache  blurred_and_distorted_vision  \
0           1            1         0                             1   
1           0            1         1                             1   
2           1            0         1                             1   
3           1            1         0                             1   
4           1            1         1                             0   
...       ...          ...       ...                           ...   
1065        0            1         0                             0   
1066        0            1         0                             0   
1067        1            1         0                             0   
1069        0            1         0                             0   
1070        0            1         0                             0   

      excessive_hunger  muscle_weakness  stiff_neck  swelling_joints  \
0                    1                0           1                0   
1                    1                0           1                0   
2                    1                0           1                0   
3                    1                0           1                0   
4                    1                1           1                0   
...                ...              ...         ...              ...   
1065                 0                0           0                0   
1066                 0                0           0                0   
1067                 0                0           0                0   
1069                 0                0           0                0   
1070                 0                0           0                0   

      movement_stiffness  depression  ...  blood_in_stool  gnawing  \
0                      0           1  ...               0        0   
1                      0           1  ...               0        0   
2                      0           0  ...               0        0   
3                      0           0  ...               0        0   
4                      0           0  ...               0        0   
...                  ...         ...  ...             ...      ...   
1065                   0           0  ...               0        0   
1066                   0           0  ...               0        0   
1067                   0           0  ...               0        0   
1069                   0           0  ...               0        0   
1070                   0           0  ...               0        0   

      upper_abdomain_pain  fullness_feeling  hiccups  abdominal_bloating  \
0                       0                 0        0                   0   
1                       0                 0        0                   0   
2                       0                 0        0                   0   
3                       0                 0        0                   0   
4                       0                 0        0                   0   
...                   ...               ...      ...                 ...   
1065                    0                 0        0                   0   
1066                    0                 0        0                   1   
1067                    0                 0        0                   1   
1069                    0                 0        0                   0   
1070                    0                 0        0                   1   

      heartburn  belching  burning_ache  prognosis  
0             0         0             0   Migraine  
1             0         0             0   Migraine  
2             0         0             0   Migraine  
3             0         0             0   Migraine  
4             0         0             0   Migraine  
...         ...       ...           ...        ...  
1065          1         1             0  Gastritis  
1066          0         1             0  Gastritis  
1067          0         0             0  Gastritis  
1069          0 

In [4]:
df.isnull().values.any()

False

# one hot encoding categorical values

In [106]:
from sklearn.preprocessing import OneHotEncoder

In [107]:
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

Index(['prognosis'], dtype='object')

In [108]:
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')

In [109]:
encoded_cols = encoder.fit_transform(df[categorical_cols])
encoded_cols

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [110]:
encoded_df = pd.DataFrame(encoded_cols, columns=encoder.get_feature_names(categorical_cols))
encoded_df

/Users/ayangairola/miniconda3/envs/deep_learning/lib/python3.11/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


prognosis_Arthritis  prognosis_Diarrhea  prognosis_Gastritis  \
0                    0.0                 0.0                  0.0   
1                    0.0                 0.0                  0.0   
2                    0.0                 0.0                  0.0   
3                    0.0                 0.0                  0.0   
4                    0.0                 0.0                  0.0   
..                   ...                 ...                  ...   
771                  0.0                 0.0                  1.0   
772                  0.0                 0.0                  1.0   
773                  0.0                 0.0                  1.0   
774                  0.0                 0.0                  1.0   
775                  0.0                 0.0                  1.0   

     prognosis_Migraine  
0                   1.0  
1                   1.0  
2                   1.0  
3                   1.0  
4                   1.0  
..                  ...  
771                 0.0  
772                 0.0  
773                 0.0  
774                 0.0  
775                 0.0  

[776 rows x 4 columns]

In [111]:
df = df.drop(categorical_cols, axis=1)
df

acidity  indigestion  headache  blurred_and_distorted_vision  \
0           1            1         0                             1   
1           0            1         1                             1   
2           1            0         1                             1   
3           1            1         0                             1   
4           1            1         1                             0   
...       ...          ...       ...                           ...   
1065        0            1         0                             0   
1066        0            1         0                             0   
1067        1            1         0                             0   
1069        0            1         0                             0   
1070        0            1         0                             0   

      excessive_hunger  muscle_weakness  stiff_neck  swelling_joints  \
0                    1                0           1                0   
1                    1                0           1                0   
2                    1                0           1                0   
3                    1                0           1                0   
4                    1                1           1                0   
...                ...              ...         ...              ...   
1065                 0                0           0                0   
1066                 0                0           0                0   
1067                 0                0           0                0   
1069                 0                0           0                0   
1070                 0                0           0                0   

      movement_stiffness  depression  ...  cramping  blood_in_stool  gnawing  \
0                      0           1  ...         0               0        0   
1                      0           1  ...         0               0        0   
2                      0           0  ...         0               0        0   
3                      0           0  ...         0               0        0   
4                      0           0  ...         0               0        0   
...                  ...         ...  ...       ...             ...      ...   
1065                   0           0  ...         0               0        0   
1066                   0           0  ...         0               0        0   
1067                   0           0  ...         0               0        0   
1069                   0           0  ...         0               0        0   
1070                   0           0  ...         0               0        0   

      upper_abdomain_pain  fullness_feeling  hiccups  abdominal_bloating  \
0                       0                 0        0                   0   
1                       0                 0        0                   0   
2                       0                 0        0                   0   
3                       0                 0        0                   0   
4                       0                 0        0                   0   
...                   ...               ...      ...                 ...   
1065                    0                 0        0                   0   
1066                    0                 0        0                   1   
1067                    0                 0        0                   1   
1069                    0                 0        0                   0   
1070                    0                 0        0                   1   

      heartburn  belching  burning_ache  
0             0         0             0  
1             0         0             0  
2             0         0             0  
3             0         0             0  
4             0         0             0  
...         ...       ...           ...  
1065          1         1             0  
1066          0         1             0  
1067          0         0             0  
1069  

In [112]:
df = pd.concat([df, encoded_df], axis=1)

In [113]:

df

acidity  indigestion  headache  blurred_and_distorted_vision  \
0        1.0          1.0       0.0                           1.0   
1        0.0          1.0       1.0                           1.0   
2        1.0          0.0       1.0                           1.0   
3        1.0          1.0       0.0                           1.0   
4        1.0          1.0       1.0                           0.0   
..       ...          ...       ...                           ...   
768      NaN          NaN       NaN                           NaN   
769      NaN          NaN       NaN                           NaN   
771      NaN          NaN       NaN                           NaN   
773      NaN          NaN       NaN                           NaN   
774      NaN          NaN       NaN                           NaN   

     excessive_hunger  muscle_weakness  stiff_neck  swelling_joints  \
0                 1.0              0.0         1.0              0.0   
1                 1.0              0.0         1.0              0.0   
2                 1.0              0.0         1.0              0.0   
3                 1.0              0.0         1.0              0.0   
4                 1.0              1.0         1.0              0.0   
..                ...              ...         ...              ...   
768               NaN              NaN         NaN              NaN   
769               NaN              NaN         NaN              NaN   
771               NaN              NaN         NaN              NaN   
773               NaN              NaN         NaN              NaN   
774               NaN              NaN         NaN              NaN   

     movement_stiffness  depression  ...  fullness_feeling  hiccups  \
0                   0.0         1.0  ...               0.0      0.0   
1                   0.0         1.0  ...               0.0      0.0   
2                   0.0         0.0  ...               0.0      0.0   
3                   0.0         0.0  ...               0.0      0.0   
4                   0.0         0.0  ...               0.0      0.0   
..                  ...         ...  ...               ...      ...   
768                 NaN         NaN  ...               NaN      NaN   
769                 NaN         NaN  ...               NaN      NaN   
771                 NaN         NaN  ...               NaN      NaN   
773                 NaN         NaN  ...               NaN      NaN   
774                 NaN         NaN  ...               NaN      NaN   

     abdominal_bloating  heartburn  belching  burning_ache  \
0                   0.0        0.0       0.0           0.0   
1                   0.0        0.0       0.0           0.0   
2                   0.0        0.0       0.0           0.0   
3                   0.0        0.0       0.0           0.0   
4                   0.0        0.0       0.0           0.0   
..                  ...        ...       ...           ...   
768                 NaN        NaN       NaN           NaN   
769                 NaN        NaN       NaN           NaN   
771                 NaN        NaN       NaN           NaN   
773                 NaN        NaN       NaN           NaN   
774                 NaN        NaN       NaN           NaN   

     prognosis_Arthritis  prognosis_Diarrhea  prognosis_Gastritis  \
0                    0.0                 0.0                  0.0   
1                    0.0                 0.0                  0.0   
2                    0.0                 0.0                  0.0   
3                    0.0                 0.0                  0.0   
4                    0.0                 0.0                  0.0   
..                   ...                 ...                  ...   
768                  0.0                 0.0                  1.0   
769                  0.0                 0.0                  1.0   
771                  0.0                 0.0                  1.0   
773                  0.0           

In [114]:
df = df.dropna()

In [115]:
df

acidity  indigestion  headache  blurred_and_distorted_vision  \
0        1.0          1.0       0.0                           1.0   
1        0.0          1.0       1.0                           1.0   
2        1.0          0.0       1.0                           1.0   
3        1.0          1.0       0.0                           1.0   
4        1.0          1.0       1.0                           0.0   
..       ...          ...       ...                           ...   
755      0.0          0.0       1.0                           0.0   
759      0.0          0.0       1.0                           0.0   
770      0.0          0.0       0.0                           0.0   
772      0.0          0.0       0.0                           0.0   
775      0.0          0.0       0.0                           0.0   

     excessive_hunger  muscle_weakness  stiff_neck  swelling_joints  \
0                 1.0              0.0         1.0              0.0   
1                 1.0              0.0         1.0              0.0   
2                 1.0              0.0         1.0              0.0   
3                 1.0              0.0         1.0              0.0   
4                 1.0              1.0         1.0              0.0   
..                ...              ...         ...              ...   
755               0.0              0.0         0.0              0.0   
759               0.0              0.0         0.0              0.0   
770               0.0              0.0         0.0              0.0   
772               0.0              0.0         0.0              0.0   
775               0.0              0.0         0.0              0.0   

     movement_stiffness  depression  ...  fullness_feeling  hiccups  \
0                   0.0         1.0  ...               0.0      0.0   
1                   0.0         1.0  ...               0.0      0.0   
2                   0.0         0.0  ...               0.0      0.0   
3                   0.0         0.0  ...               0.0      0.0   
4                   0.0         0.0  ...               0.0      0.0   
..                  ...         ...  ...               ...      ...   
755                 0.0         0.0  ...               0.0      0.0   
759                 0.0         0.0  ...               0.0      0.0   
770                 0.0         0.0  ...               0.0      0.0   
772                 0.0         0.0  ...               0.0      0.0   
775                 0.0         0.0  ...               0.0      0.0   

     abdominal_bloating  heartburn  belching  burning_ache  \
0                   0.0        0.0       0.0           0.0   
1                   0.0        0.0       0.0           0.0   
2                   0.0        0.0       0.0           0.0   
3                   0.0        0.0       0.0           0.0   
4                   0.0        0.0       0.0           0.0   
..                  ...        ...       ...           ...   
755                 0.0        0.0       0.0           0.0   
759                 0.0        0.0       0.0           0.0   
770                 0.0        0.0       0.0           0.0   
772                 0.0        0.0       0.0           0.0   
775                 0.0        0.0       0.0           0.0   

     prognosis_Arthritis  prognosis_Diarrhea  prognosis_Gastritis  \
0                    0.0                 0.0                  0.0   
1                    0.0                 0.0                  0.0   
2                    0.0                 0.0                  0.0   
3                    0.0                 0.0                  0.0   
4                    0.0                 0.0                  0.0   
..                   ...                 ...                  ...   
755                  0.0                 0.0                  1.0   
759                  0.0                 0.0                  1.0   
770                  0.0                 0.0                  1.0   
772                  0.0           

In [118]:
dataset = df.to_numpy()
print(dataset.shape)

(547, 35)


In [120]:
X = dataset[:,:31]
print(X)
print(X.shape)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(547, 31)


In [121]:
y = dataset[:,31:]
print(y)
print(y.shape)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
(547, 4)


In [122]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [123]:
print("train data :", X_train.shape)
print("\ntest data :", X_test.shape)
print("\ntrain target :", y_train.shape)
print("\ntest target :",y_test.shape)

train data : (437, 31)

test data : (110, 31)

train target : (437, 4)

test target : (110, 4)


In [202]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,  Dropout
from tensorflow.keras import regularizers

In [233]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [259]:
model = Sequential()
model.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.01), input_shape=(X_train_scaled.shape[1],)))
model.add(Dropout(0.4))
model.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.4))
model.add(Dense(4, activation='softmax'))

In [260]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [261]:
model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/10
14/14 [==============================] - 0s 4ms/step - loss: 2.4318 - accuracy: 0.3982 - val_loss: 2.0319 - val_accuracy: 0.7091
Epoch 2/10
14/14 [==============================] - 0s 1ms/step - loss: 2.1607 - accuracy: 0.5309 - val_loss: 1.8257 - val_accuracy: 0.8091
Epoch 3/10
14/14 [==============================] - 0s 1ms/step - loss: 1.9035 - accuracy: 0.6156 - val_loss: 1.6928 - val_accuracy: 0.7818
Epoch 4/10
14/14 [==============================] - 0s 996us/step - loss: 1.8036 - accuracy: 0.6178 - val_loss: 1.5678 - val_accuracy: 0.8091
Epoch 5/10
14/14 [==============================] - 0s 1ms/step - loss: 1.6575 - accuracy: 0.6590 - val_loss: 1.4651 - val_accuracy: 0.8091
Epoch 6/10
14/14 [==============================] - 0s 1ms/step - loss: 1.5838 - accuracy: 0.6842 - val_loss: 1.3787 - val_accuracy: 0.8091
Epoch 7/10
14/14 [==============================] - 0s 1ms/step - loss: 1.5192 - accuracy: 0.6773 - val_loss: 1.3136 - val_accuracy: 0.8182
Epoch 8/10
14/14 [

In [262]:
y_pred = model.predict(X_test_scaled)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(np.array(y_test), axis=1)

# Calculate the accuracy score
accuracy = accuracy_score(y_test_classes, y_pred_classes)
print(f'Accuracy: {accuracy}')

4/4 [==============================] - 0s 543us/step
Accuracy: 0.8
